# Generated by Django 4.2.16 on 2024-11-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('year_of_study', models.CharField(choices=[('Y_1', 'Year 1'), ('Y_2', 'Year 2'), ('Y_3', 'Year 3'), ('Y_4', 'Year 4')], default='Y_1', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
                ('Bio', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='default.jpj')),
            ],
        ),
        migrations.CreateModel(
            name='intake',
            fields=[
                ('intake_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=30)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('replay', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=500)),
                ('likes', models.ManyToManyField(related_name='liked_challenges', to='main.user')),
                ('user', models.ManyToManyField(to='main.user')),
            ],
        ),
    ]
