# Generated by Django 4.2.16 on 2024-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenges',
            options={'ordering': ['challenge_name']},
        ),
        migrations.AlterModelOptions(
            name='intake',
            options={'ordering': ['intake_id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'ordering': ['id__first_name']},
        ),
        migrations.AlterField(
            model_name='challenges',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='replay',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(choices=[('Y_1', 'Year 1'), ('Y_2', 'Year 2'), ('Y_3', 'Year 3'), ('Y_4', 'Year 4')], default='Y_1', max_length=6),
        ),
    ]
