# Generated by Django 4.2.16 on 2024-11-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_challenges_options_alter_intake_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'ordering': ['user__first_name']},
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='challenges',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_challenges', to='main.user'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='main.user'),
        ),
    ]
