# Generated by Django 4.2.16 on 2024-11-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='Bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='default.jpj'),
        ),
    ]
