# Generated by Django 4.2.16 on 2024-11-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_profile_bio_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_challenges', to='main.user'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='replay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='user',
            field=models.ManyToManyField(blank=True, to='main.user'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.challenges')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.user')),
            ],
        ),
    ]
