# Generated by Django 4.2.16 on 2024-11-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_challenges_comment_remove_challenges_replay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='parent',
            new_name='parent_reply',
        ),
    ]
