# Generated by Django 4.2.16 on 2024-11-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_parent_review_parent_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='user',
        ),
        migrations.AddField(
            model_name='challenges',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Challenge', to='main.user'),
        ),
    ]
