# Generated by Django 4.2.16 on 2024-11-30 16:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_challenges_user_challenges_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkChallengeContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default="My Bookmark's challenge", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_containers', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkChallengeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_items', to='main.challenges')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_challenge_items', to='main.bookmarkchallengecontainer')),
            ],
        ),
    ]
