# Generated by Django 4.2.16 on 2024-11-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookmarkchallengecontainer_bookmarkchallengeitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkchallengecontainer',
            old_name='name',
            new_name='bookmark_name',
        ),
    ]
