# Generated by Django 4.2.16 on 2024-11-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_name_bookmarkchallengecontainer_bookmark_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkchallengecontainer',
            name='updated_at',
        ),
    ]
