# Generated by Django 4.2.16 on 2024-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='year_of_study',
            field=models.CharField(choices=[('Y_1', 'Year 1'), ('Y_2', 'Year 2'), ('Y_3', 'Year 3'), ('Y_4', 'Year 4')], default='Y_1', max_length=6),
        ),
    ]
