# Generated by Django 4.2.16 on 2024-12-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_user_year_of_study_user_profile_year_of_study'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_profile',
            new_name='Student',
        ),
    ]
