# Generated by Django 4.2.16 on 2024-12-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_bookmarkchallengecontainer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='intake',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
