# Generated by Django 4.2.16 on 2024-12-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_options'),
        ('main', '0019_remove_student_user_delete_intake_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Panding'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student')),
            ],
            options={
                'permissions': [('canel_order', 'Can cancel order')],
            },
        ),
    ]
