# Generated by Django 4.2.16 on 2024-12-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_orderingfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingFeedBackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='main.challenges')),
                ('odering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odering_feedback_items', to='main.orderingfeedback')),
            ],
        ),
    ]
