# Generated by Django 4.2.16 on 2024-12-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_orderingfeedbackitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkchallengecontainer',
            old_name='id',
            new_name='container_id',
        ),
    ]
