# Generated by Django 4.2.16 on 2024-12-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_id_bookmarkchallengecontainer_container_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkchallengecontainer',
            old_name='container_id',
            new_name='id',
        ),
    ]
