# Generated by Django 4.2.16 on 2024-12-03 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year_of_study', models.CharField(choices=[('Y_1', 'Year 1'), ('Y_2', 'Year 2'), ('Y_3', 'Year 3'), ('Y_4', 'Year 4')], default='Y_1', max_length=6)),
                ('Bio', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='default.jpj')),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='intake',
            fields=[
                ('intake_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['intake_id'],
            },
        ),
    ]
