# Generated by Django 4.2.16 on 2024-12-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_intake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__first_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
